server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

okta:
  oauth2:
    issuer: https://dev-110uie3k4jjd8cey.us.auth0.com/
    audience: localhost/api/v1/weather
    client-id: JpuDQyqEAgLi5bShYQiOnnE3jSd5p2NS
    client-secret: KXNirbKbgTy3qThwyNEou68ypm7aXvZWks9SlIRMbWSW9lDrjd38Kdso9ZTFuLJN
    groups-claim: client_credentials

services:
  open-weather-map: https://api.openweathermap.org/data/2.5/weather
  auth: https://dev-110uie3k4jjd8cey.us.auth0.com/oauth

app:
  secrets:
    open-weather:
      app-id: ab9da5dbd643711d7007d938b2accf3a
    oauth:
      client-id: JpuDQyqEAgLi5bShYQiOnnE3jSd5p2NS
      client-secret: KXNirbKbgTy3qThwyNEou68ypm7aXvZWks9SlIRMbWSW9lDrjd38Kdso9ZTFuLJN
      audience: localhost/api/v1/weather
      grant-type: client_credentials