server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

services:
  open-weather-map: https://api.openweathermap.org/data/2.5/weather

app:
  secrets:
    open-weather:
      app-id: ab9da5dbd643711d7007d938b2accf3a
